export enum EnvEnum {
  PORT = 'PORT',
  PROBATION_API_URL = 'PROBATION_API_URL',
  PROBATION_API_KEY = 'PROBATION_API_KEY',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  DB_TYPE = 'DB_TYPE',
}
